export const assets = {
    hair: [
      require('@/assets/character/hair/hair1.png'),
      require('@/assets/character/hair/hair2.png'),
      require('@/assets/character/hair/hair3.png'),      
      require('@/assets/character/hair/hair4.png'),      
      require('@/assets/character/hair/hair5.png'),      
      require('@/assets/character/hair/hair6.png'),      
      require('@/assets/character/hair/hair7.png'),      
      require('@/assets/character/hair/hair8.png'),      
      require('@/assets/character/hair/hair9.png'),        
    ],
    face: [
      require('@/assets/character/face/face1.png'),
      require('@/assets/character/face/face2.png'),
      require('@/assets/character/face/face3.png'),
      require('@/assets/character/face/face4.png'),
      require('@/assets/character/face/face5.png'),
      require('@/assets/character/face/face6.png'),
      require('@/assets/character/face/face7.png'),
      require('@/assets/character/face/face8.png'),
      require('@/assets/character/face/face9.png'),
      require('@/assets/character/face/face10.png'),
      require('@/assets/character/face/face11.png'),
      require('@/assets/character/face/face12.png'),
      require('@/assets/character/face/face13.png'),
      require('@/assets/character/face/face14.png'),
      require('@/assets/character/face/face15.png'),
    ],
    body: [
      require('@/assets/character/body/body1.png'),
      require('@/assets/character/body/body2.png'),
      require('@/assets/character/body/body3.png'),
      require('@/assets/character/body/body4.png'),
      require('@/assets/character/body/body5.png'),
      require('@/assets/character/body/body6.png'),
    ],
  };